spring:
  datasource:
    url: jdbc:postgresql://ec2-54-225-228-142.compute-1.amazonaws.com:5432/df2s2mk6vf9pkh
    username: vdayzamtfimrdb
    password: 7da0c43bd1bf59a9dd9c3bdcdf3113fc76efeb08fa147673af4f18865e703e21
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true